### PR TITLE
Added support for Pipeline jobs

### PR DESCRIPTION
**Pull request by abeeskau**
Changes will allow a user to create a **Pipeline job** and enable "_Trigger build when a message is published to an Amazon SQS queue_".

### CODE REVIEW

**Comment by prat0318** [comment]
+1 for this

**Comment by roribio** [comment]
+1 for this!

**Comment by burtino** [comment]
+1 Thanks abeeksau!

**Comment by prat0318** [comment]
Is there a way i can manually use this patch till a new version is cut?

**Comment by abeeskau** [comment]
@prat0318 you could pull in the changes from my branch and build it locally.  Then, from the Plugin Manager -> Advanced tab; Upload the hpi file that you built.

**Comment by prat0318** [comment]
@abeeskau thanks so much. That worked!

**Comment by frezbo** [comment]
@abeeskau  I see that the pipeline job gets triggered first time on data being added to SQS, but not on subsequent SQS polls

**Comment by abeeskau** [comment]
@frezbo I am using a FIFO sqs queue (with content-based deduplication enabled).  Each time I add a message to the queue, my job that is tied to that queue gets triggered.

**Comment by joe-niland** [comment]
Hi @abeeskau just wondering if there are any other steps you have to do after uploading the custom built hpi file. I've tried this with Jenkins 2.73 but the additional checkbox doesn't show up in the Configure page for the pipeline. Thanks for your work on this feature!

**Comment by abeeskau** [comment]
Hi @joe-niland I just it on a Jenkins 2.73 installation and I am able to see the additional checkbox.

image

**Comment by abeeskau** [comment]
@nickgrealy please let me know if you need anymore details so that this change can be merged.

**Comment by nickgrealy** [comment]
@abeeskau thanks for the PR and sorry for not being on top of this. Changes look good, I'm just pushing a new release now.

**Comment by joe-niland** [comment]
Hi @abeeskau thanks for clarifying. I'll try again with the new release.

**Comment by ayashjorden** [comment]
Hi @abeeskau,

First, thank you for adding this functionality :)

I've installed version 2.0.1 of this plugin, but I don't see SQS steps in the Pipeline code generator.
Where should I look for documentation?

Thank you,
Yarden

**Comment by abeeskau** [comment]
Hi @ayashjorden -

To my knowledge, this plugin does not expose functionality via pipeline steps.  Everything is at the job configuration level.  You would enable "_Trigger build when a message is published..._" and specify the "_SQS queue to monitor_".  Also, what was not obvious to me until I looked more closely at [the code](https://github.com/jenkinsci/aws-sqs-plugin/blob/master/src/main/java/io/relution/jenkins/awssqs/SQSTrigger.java#L203-L206) was that your job must also contain the following parameters - **sqs_body**, **sqs_messageId**, **sqs_receiptHandle**, **sqs_bodyMD5**.

Ann

**Comment by ayashjorden** [comment]
Hi @abeeskau,
I understand that Pipeline code doesn't handle [job triggers](https://jenkins.io/doc/book/pipeline/syntax/#triggers)?

I understood the job parameters thing when the plugin didn't work for me at back when I started working with it :), but thank you for clarifying that 👍 

My original goal is _to avoid having multiple jobs for triggering from SQS_ because in my scenario, I'm required to **read from multiple SQS queues**, so was hoping to be able to configure multiple SQS triggers in the same job (which, in turn, will trigger downstream jobs.)

Should this ^^^ be posted in a new "issue"?

Thank you,
Jorden

**Comment by prat0318** [comment]
Hi @abeeskau , suddenly after Jenkins restart, i noticed that `$sqs_body` stopped getting populated in the pipeline job. It had been working well with deployment of just this patch and manual jenkins build. Not sure how jenkins restart screwed up things. I still see job being triggered with SQS, so plugin works. Just that no environment variable gets set.

**Pull request merged**
